FROM --platform=linux/amd64 python:3.11.6-bookworm

WORKDIR /backend

RUN apt update && \
    apt install -y git chromium pandoc texlive-latex-base texlive-latex-recommended 

RUN pip install --upgrade pip poetry
COPY ./pyproject.toml /backend/
COPY ./README.md /backend/README.md

RUN poetry install --with workers --no-root

ENV JVOY_DOCKER=1
# set display port to avoid crash. TODO Needed?
ENV DISPLAY=:99
