import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "primeflex/primeflex.css";
import 'primeicons/primeicons.css';

// import "primereact/resources/themes/fluent-light/theme.css";
import "primereact/resources/themes/bootstrap4-dark-blue/theme.css";

import styles from "./layout.module.scss";

import { PrimeReactProvider } from 'primereact/api';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <PrimeReactProvider>
          <div className={styles.siteWrapper}>
            {children}
          </div>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
